base_url = "https://github.com/jinho-choi123/zola-gitbook-theme/"
compile_sass = true
title = "book theme"
description = "A book theme"
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "css"

[extra]
book_number_chapters = true
book_only_current_section_pages = false
katex_enable = true
katex_auto_render = true
